import type { Metadata, Viewport } from "next";
import "@/assets/globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Header from "@/components/shared/layout/header/Header";
import TilesHeader from "@/components/shared/TilesHeader";
import Footer from "@/components/shared/layout/header/footer";

export const metadata: Metadata = {
  title: "Fan page",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable.css"
        />
      </head>
      <body className="font-pretendard">
        <Header />
        <TilesHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
